   name: Test my website
   on: [push]
   jobs:
     check-html:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Check if index.html exists
           run: test -f index.html
         - name: Check for word DevOps
           run: grep "DevOps" index.html
